#include <Servo.h>

Servo servo_pin_9;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}


void setup()
{
  pinMode( 10 , INPUT);
  Serial.begin(9600);
  pinMode(11, INPUT_PULLUP);
  pinMode( 7 , OUTPUT);
  servo_pin_9.attach(9);
  digitalWrite( 3 , LOW );

}

void loop()
{
  Serial.print("potentiometer:");
  Serial.print(analogRead(2));
  Serial.println();
  Serial.print("Sound Sensor Data:");
  Serial.print(digitalRead(10));
  Serial.println();
  if (	digitalRead(11) == LOW )
  {
    if (( ( digitalRead(10) ) == ( HIGH ) ))
    {
      digitalWrite( 7 , HIGH );
      servo_pin_9.write( 90 );
      delay( 3000 );
      servo_pin_9.write( 1 );
      digitalWrite( 7 , LOW );
      delay( 3000 );
    }
    else
    {
      servo_pin_9.write( 1 );
      digitalWrite( 7 , LOW );
    }
  }
  else
  {
    if (( ( 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 3 , 4 ) ) < ( 5 ) ))
    {
      digitalWrite( 7 , HIGH );
      servo_pin_9.write( 90 );
      if (( ( analogRead(2) ) < ( 500 ) ))
      {
        delay( 3000 );
      }
      else
      {
        delay( 500 );
      }
      servo_pin_9.write( 1 );
      digitalWrite( 7 , LOW );
    }
    else
    {
      servo_pin_9.write( 1 );
      digitalWrite( 7 , LOW );
    }
  }
}

